In [1]:
import pandas as pd

In [2]:
# import data set to df
df = pd.read_csv('database.csv')
df.head()

C:\Users\cmilb\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (16) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,Record ID,Agency Code,Agency Name,Agency Type,City,State,Year,Month,Incident,Crime Type,...,Victim Ethnicity,Perpetrator Sex,Perpetrator Age,Perpetrator Race,Perpetrator Ethnicity,Relationship,Weapon,Victim Count,Perpetrator Count,Record Source
0,1,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,January,1,Murder or Manslaughter,...,Unknown,Male,15,Native American/Alaska Native,Unknown,Acquaintance,Blunt Object,0,0,FBI
1,2,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,March,1,Murder or Manslaughter,...,Unknown,Male,42,White,Unknown,Acquaintance,Strangulation,0,0,FBI
2,3,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,March,2,Murder or Manslaughter,...,Unknown,Unknown,0,Unknown,Unknown,Unknown,Unknown,0,0,FBI
3,4,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,April,1,Murder or Manslaughter,...,Unknown,Male,42,White,Unknown,Acquaintance,Strangulation,0,0,FBI
4,5,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,April,2,Murder or Manslaughter,...,Unknown,Unknown,0,Unknown,Unknown,Unknown,Unknown,0,1,FBI

In [ ]:
list(df.columns.values)

In [43]:
counts= df.groupby(['State', 'Year']).agg({'Year':['count']})
counts.reset_index(inplace = True)
counts.head(100)

      State  Year
                  count
0   Alabama  1980   513
1   Alabama  1981   453
2   Alabama  1982   424
3   Alabama  1983   372
4   Alabama  1984   382
..      ...   ...   ...
95  Arizona  2006   509
96  Arizona  2007   516
97  Arizona  2008   403
98  Arizona  2009   370
99  Arizona  2010   400

[100 rows x 3 columns]

In [31]:
state_df = df.groupby(['State'])
state_df.head()

,Record ID,Agency Code,Agency Name,Agency Type,City,State,Year,Month,Incident,Crime Type,...,Victim Ethnicity,Perpetrator Sex,Perpetrator Age,Perpetrator Race,Perpetrator Ethnicity,Relationship,Weapon,Victim Count,Perpetrator Count,Record Source
0,1,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,January,1,Murder or Manslaughter,...,Unknown,Male,15,Native American/Alaska Native,Unknown,Acquaintance,Blunt Object,0,0,FBI
1,2,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,March,1,Murder or Manslaughter,...,Unknown,Male,42,White,Unknown,Acquaintance,Strangulation,0,0,FBI
2,3,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,March,2,Murder or Manslaughter,...,Unknown,Unknown,0,Unknown,Unknown,Unknown,Unknown,0,0,FBI
3,4,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,April,1,Murder or Manslaughter,...,Unknown,Male,42,White,Unknown,Acquaintance,Strangulation,0,0,FBI
4,5,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,April,2,Murder or Manslaughter,...,Unknown,Unknown,0,Unknown,Unknown,Unknown,Unknown,0,1,FBI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23058,23059,WY00101,Laramie,Municipal Police,Albany,Wyoming,1980,February,1,Murder or Manslaughter,...,Not Hispanic,Male,19,White,Not Hispanic,Acquaintance,Rifle,0,0,FBI
23059,23060,WY00300,Campbell,Sheriff,Campbell,Wyoming,1980,August,1,Murder or Manslaughter,...,Unknown,Male,39,Black,Unknown,Acquaintance,Shotgun,0,0,FBI
23060,23061,WY00400,Carbon,Sheriff,Carbon,Wyoming,1980,April,1,Murder or Manslaughter,...,Not Hispanic,Male,31,White,Not Hispanic,Acquaintance,Blunt Object,0,1,FBI
23061,23062,WY00400,Carbon,Sheriff,Carbon,Wyoming,1980,August,1,Murder or Manslaughter,...,Unknown,Male,38,White,Unknown,Acquaintance,Rifle,0,0,FBI
23062,23063,WY00401,Rawlins,Municipal Police,Carbon,Wyoming,1980,December,1,Murder or Manslaughter,...,Not Hispanic,Male,18,White,Not Hispanic,Acquaintance,Knife,0,0,FBI

In [39]:
year = df.groupby(['Year'])
year.head()

,Record ID,Agency Code,Agency Name,Agency Type,City,State,Year,Month,Incident,Crime Type,...,Victim Ethnicity,Perpetrator Sex,Perpetrator Age,Perpetrator Race,Perpetrator Ethnicity,Relationship,Weapon,Victim Count,Perpetrator Count,Record Source
0,1,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,January,1,Murder or Manslaughter,...,Unknown,Male,15,Native American/Alaska Native,Unknown,Acquaintance,Blunt Object,0,0,FBI
1,2,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,March,1,Murder or Manslaughter,...,Unknown,Male,42,White,Unknown,Acquaintance,Strangulation,0,0,FBI
2,3,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,March,2,Murder or Manslaughter,...,Unknown,Unknown,0,Unknown,Unknown,Unknown,Unknown,0,0,FBI
3,4,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,April,1,Murder or Manslaughter,...,Unknown,Male,42,White,Unknown,Acquaintance,Strangulation,0,0,FBI
4,5,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,April,2,Murder or Manslaughter,...,Unknown,Unknown,0,Unknown,Unknown,Unknown,Unknown,0,1,FBI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
624123,624124,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,2014,March,1,Murder or Manslaughter,...,Unknown,Unknown,0,Unknown,Unknown,Unknown,Firearm,1,0,FBI
624124,624125,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,2014,January,1,Murder or Manslaughter,...,Unknown,Unknown,0,Unknown,Unknown,Unknown,Firearm,0,0,FBI
624125,624126,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,2014,January,2,Manslaughter by Negligence,...,Unknown,Female,64,White,Unknown,Unknown,Fire,0,0,FBI
624126,624127,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,2014,February,1,Murder or Manslaughter,...,Unknown,Male,19,White,Unknown,Neighbor,Firearm,0,0,FBI
624127,624128,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,2014,March,1,Murder or Manslaughter,...,Unknown,Unknown,0,Unknown,Unknown,Unknown,Firearm,1,0,FBI

In [28]:
# count of homicide by state
state_homicide_count_state= state_df['Crime Type'].count()

State
Alabama                 11376
Alaska                   1617
Arizona                 12871
Arkansas                 6947
California              99783
Colorado                 6593
Connecticut              4896
Delaware                 1179
District of Columbia     7115
Florida                 37164
Georgia                 21088
Hawaii                   1338
Idaho                    1150
Illinois                25871
Indiana                 11463
Iowa                     1749
Kansas                   3085
Kentucky                 6554
Louisiana               19629
Maine                     869
Maryland                17312
Massachusetts            6036
Michigan                28448
Minnesota                3975
Mississippi              6546
Missouri                14832
Montana                   601
Nebraska                 1331
Nevada                   5553
New Hampshire             655
New Jersey              14132
New Mexico               4272
New York                49268
North Carolina          20390
North Dakota              308
Ohio                    19158
Oklahoma                 8809
Oregon                   4217
Pennsylvania            24236
Rhodes Island            1211
South Carolina          11698
South Dakota              442
Tennessee               14930
Texas                   62095
Utah                     2033
Vermont                   412
Virginia                15520
Washington               7815
West Virginia            3061
Wisconsin                6191
Wyoming                   630
Name: Crime Type, dtype: int64

In [23]:
homicide_counts = state_homicide_count_year['Crime Type'].count()

In [40]:
murder_counts = {'State': state_df,
                 'Year': year,
    'Total Murder': state_homicide_count_state
}
murder_totals = pd.DataFrame(murder_counts)
murder_totals.head()

C:\Users\cmilb\anaconda3\lib\site-packages\pandas\core\dtypes\cast.py:1229: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  v = np.array(v, copy=False)
C:\Users\cmilb\anaconda3\lib\site-packages\pandas\core\dtypes\cast.py:1623: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  subarr = np.array(values, dtype=dtype, copy=copy)
C:\Users\cmilb\anaconda3\lib\site-packages\numpy\core\_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)

ValueError: could not broadcast input array from shape (35) into shape (51)